/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardCoachChatRouteImport } from './routes/dashboard/coach-chat'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoachChatRoute = DashboardCoachChatRouteImport.update({
  id: '/dashboard/coach-chat',
  path: '/dashboard/coach-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/coach-chat': typeof DashboardCoachChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/coach-chat': typeof DashboardCoachChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/coach-chat': typeof DashboardCoachChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/pricing'
    | '/checkout/success'
    | '/dashboard/coach-chat'
    | '/dashboard/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/pricing'
    | '/checkout/success'
    | '/dashboard/coach-chat'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/pricing'
    | '/checkout/success'
    | '/dashboard/coach-chat'
    | '/dashboard/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DashboardCoachChatRoute: typeof DashboardCoachChatRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/coach-chat': {
      id: '/dashboard/coach-chat'
      path: '/dashboard/coach-chat'
      fullPath: '/dashboard/coach-chat'
      preLoaderRoute: typeof DashboardCoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DashboardCoachChatRoute: DashboardCoachChatRoute,
  DashboardProfileRoute: DashboardProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
